### ISSUE TITLE
This my just be me but in ubuntu...

### ISSUE THREAD

**Issue by fenderrex** [fables-tales/spe#6]
I haven't seen any of these issues on git...  
I am asking where to start working hoping someone can point to a file and dir ect
This may just be me but in ubuntu SPE crashes on saving and occasionally in pasting or cutting it crashes 
- Pasting or cutting SPE crashes.(or Explorer will lose index/freez then SPE will crash)
- While saving, occasionally SPE crashes.(ctrl+s)

just incase miss matching packages are a problem... 
Spe version 
0.8.4.h 
Python version 
2.7.6  (2.3 required) 
wxPython version 
2.8.12.1  (2.6.1.0. required)

**Comment by fables-tales** [comment]
@fenderrex this is almost certainly not the SPE project you are looking for. SPE was a project done by myself and the other contributors on this repo in our second year of university. It looks like you're looking for the maintainers of a SPE package, for which I can't help you. Sorry
